//! Build script: the Tauri codegen plus the interface message catalog.
//!
//! `public/messages.json` is the single source of every user-visible message:
//! this script validates it through the shared `catalog` module (identifier,
//! both-languages and placeholder rules live in catalog.rs) and renders it into
//! `OUT_DIR/messages.rs` — the running shell only ever sees the generated
//! `MessageId` enum and its `&'static str` templates, never the JSON and never
//! a map.

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

mod catalog;

/// The catalog, relative to the package root (the directory next to this one
/// holds `public/`). Also the path Cargo watches for rebuilds.
const CATALOG_RELATIVE: &str = "../public/messages.json";

fn main() {
    println!("cargo:rerun-if-changed=icons/icon.png");
    println!("cargo:rerun-if-changed=icons/icon.ico");
    println!("cargo:rerun-if-changed={CATALOG_RELATIVE}");
    // The validator is a module of this script; watch its source explicitly.
    println!("cargo:rerun-if-changed=catalog.rs");
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .windows_attributes(
                tauri_build::WindowsAttributes::new().window_icon_path("icons/icon.ico"),
            )
            .app_manifest(tauri_build::AppManifest::new().commands(&[
                "overlay_ready",
                "capture_started",
                "capture_finalizing",
                "finish_session",
                "insert_text",
                "start_native_capture",
                "stop_native_capture",
                "mute_warning_shown",
                "lab_prepare_capture",
                "lab_start_capture",
                "lab_stop_capture",
                "dictation_context",
                "settings_open",
                "settings_update_general",
                "settings_list_input_devices",
                "settings_set_keys",
                "settings_reveal_keys",
                "settings_clear_keys",
                "settings_check_keys",
                "settings_apply_keys",
                "settings_close",
                "settings_action",
                "settings_update_hotkey",
                "settings_hotkey_capture",
                "settings_set_autostart",
            ])),
    )
    .expect("Tauri command permission generation failed");

    generate_messages();
}

/// Validate the catalog through the shared `catalog` module and render
/// `OUT_DIR/messages.rs`.
fn generate_messages() {
    let catalog_path =
        Path::new(&env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set"))
            .join(CATALOG_RELATIVE);
    let text = fs::read_to_string(&catalog_path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", catalog_path.display()));
    let messages = catalog::parse_catalog(&text)
        .unwrap_or_else(|error| panic!("{} is invalid: {error}", catalog_path.display()));
    write_messages(&messages);
}

/// Render the generated source: the enum, its wire keys and its templates.
fn write_messages(messages: &BTreeMap<String, (String, String)>) {
    let mut out = String::new();
    out.push_str("// @generated by build.rs from public/messages.json; do not edit.\n\n");
    out.push_str("/// Every user-visible interface message, by its catalog key.\n");
    out.push_str(
        "#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]\n",
    );
    out.push_str("pub enum MessageId {\n");
    for key in messages.keys() {
        writeln!(out, "    {key},").expect("writing the message enum");
    }
    out.push_str("}\n\n");

    out.push_str("impl MessageId {\n");
    out.push_str("    /// The wire key: the identifier exactly as the catalog spells it.\n");
    out.push_str("    pub fn as_str(self) -> &'static str {\n        match self {\n");
    for key in messages.keys() {
        writeln!(out, "            MessageId::{key} => \"{key}\",").expect("writing as_str");
    }
    out.push_str("        }\n    }\n\n");

    out.push_str("    /// Resolve a wire key (or identifier) back to its variant.\n");
    out.push_str("    pub fn from_key(key: &str) -> Option<MessageId> {\n        match key {\n");
    for key in messages.keys() {
        writeln!(out, "            \"{key}\" => Some(MessageId::{key}),")
            .expect("writing from_key");
    }
    out.push_str("            _ => None,\n        }\n    }\n\n");

    out.push_str("    /// The template in the requested language.\n");
    out.push_str(
        "    pub fn template(self, language: Language) -> &'static str {\n        match self {\n",
    );
    for (key, (en, ru)) in messages {
        writeln!(out, "            MessageId::{key} => match language {{")
            .expect("writing a template arm");
        writeln!(out, "                Language::En => {en:?},")
            .expect("writing the en template");
        writeln!(out, "                Language::Ru => {ru:?},")
            .expect("writing the ru template");
        out.push_str("            },\n");
    }
    out.push_str("        }\n    }\n}\n");

    let path = Path::new(&env::var("OUT_DIR").expect("OUT_DIR is set for build scripts"))
        .join("messages.rs");
    fs::write(&path, out)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", path.display()));
}
